name: env
channels:
  - defaults
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - gcc_linux-64
  - libgcc
  - pip 
  - matplotlib
  - numpy
  - pandas
  - pybedtools
  - pybigwig
  - pysam
  - python=3.10
  - scikit-learn
  - scipy
  - seaborn
  - samtools
  - bedtools
  - bwa
  - bowtie2
  - pip:
    - cooler
    - cooltools
    - tensorflow==2.12.0